
title: My Resume
baseurl: '/nooshinyousefzadeh' #change it according to your repository name



# Profile information
yourname: Nooshin Yousefzadeh  ## put your name
title: 'Computer &amp; Information Scientist'  ## your title
location: Gainesville , FL


## Social Profiles
X: https://x.com/nooshin_yfz/
scholar: https://scholar.google.com/citations?user=so_ij1oAAAAJ&hl=en&oi=sra
linkedin: https://www.linkedin.com/in/nooshin-yousefzadeh-30314a73/
researchgate: https://www.researchgate.net/profile/Nooshin-Yousefzadeh-3



# Update all the sections by editing the files inside _includes folder.
